In [15]:
#one dimensional
import numpy as np
N=np.array([1,2,3,4,5,7])
print(N)
print(N[2:5])
#Array[start:end:step]
#2 dimensional
M=np.array([[1,2,3],[4,5,6]])
print(M)
print(M.shape)
print(M.ndim)

[1 2 3 4 5 7]
[3 4 5]
[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [ ]:
#for loop
import numpy as np
n1=np.array([1,2,3,4])
n2=np.array([4,5,6,7])